apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: ./charts/podinfo/
      version: '4.0.x'
      sourceRef:
        kind: GitRepository
        name: podinfo
        namespace: flux-system
      interval: 1m
  values:
    replicaCount: 1
    image:
      # 6.1.[1-4]
      tag: 6.1.2
